<<<<<<< HEAD
import { Poppins } from 'next/font/google';
import "./globals.css";
import Navbar from "@/Components/Layout/Navbar";
import Footer from "@/Components/Layout/Footer";

const poppins = Poppins({ 
  weight: ['400','500','700'],
  subsets: ['latin'],
  variable: '--font-poppins',
});

export const metadata = {
  title: "Movie Matrix",
  description: "Template %s | for movie recommendation system",
=======
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/Authprovider/AuthProvider";
import Footer from "@/components/Footer";
import Link from "next/link";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 178d26141ed293347afff494238f1661194b99a1
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
<<<<<<< HEAD
        className={`${poppins.variable} antialiased`}
      >
        <header>
   <Navbar/>
        </header>
   <main className="min-h-screen bg-base-200">{children}</main>
        <footer><Footer/></footer>
=======
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Header */}
        <header className="px-5 py-2 items-center flex justify-between gap-5 bg-stone-800">
          <div className="flex gap-x-4 items-center">
            <Link href="/">
              <img
                width={60}
                height={20}
                src="/logo.png"
                alt="Logo"
                className="w-[60px] rounded-xl"
              />
            </Link>
            <h2 className="text-xl text-white font-semibold">MuvieMatrix</h2>
          </div>

          <div className="space-x-5">
            <Link className="p-2 rounded-xl bg-amber-400" href="/movies">
              Movies
            </Link>
            <Link className="p-2 rounded-xl bg-amber-400" href="/reviews">
              Reviews
            </Link>
            <Link className="p-2 rounded-xl bg-amber-400" href="/register">
              Register
            </Link>
            <Link className="p-2 rounded-xl bg-amber-400" href="/login">
              Login
            </Link>
          </div>
        </header>

        {/* Main Content */}

        <main className="flex-grow">
          <AuthProvider>{children}</AuthProvider>
        </main>

        <Footer></Footer>
>>>>>>> 178d26141ed293347afff494238f1661194b99a1
      </body>
    </html>
  );
}
