<<<<<<< HEAD
import { Poppins } from 'next/font/google';
import "./globals.css";
import Navbar from "@/Components/Layout/Navbar";
import Footer from "@/Components/Layout/Footer";

const poppins = Poppins({ 
  weight: ['400','500','700'],
  subsets: ['latin'],
  variable: '--font-poppins',
});

export const metadata = {
  title: "Movie Matrix",
  description: "Template %s | for movie recommendation system",
};

=======
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/Authprovider/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


>>>>>>> dbb59562dc05315006b63b056fce2160a57ddfab
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
<<<<<<< HEAD
        className={`${poppins.variable} antialiased`}
      >
        <header>
   <Navbar/>
        </header>
   <main className="min-h-screen bg-base-200">{children}</main>
        <footer><Footer/></footer>
=======
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
        {children}
        </AuthProvider>
>>>>>>> dbb59562dc05315006b63b056fce2160a57ddfab
      </body>
    </html>
  );
}
